name: sol

services:
  platform:
    container_name: app.platform
    profiles:
      - platform
      - api
      - app
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      azuresql:
        condition: service_started
      azurestorage:
        condition: service_healthy
      redis:
        condition: service_healthy
    hostname: app.platform.local
    ports:
      - 5051:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__TenantDb=Server=svc.sqldb.local;Database=CustomerDb;User Id=sa;Password=P@ssw0rd!;Persist Security Info=False;Encrypt=False
      - ConnectionStrings__AzureStorage=AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;QueueEndpoint=http://host.docker.internal:10001/devstoreaccount1;TableEndpoint=http://host.docker.internal:10002/devstoreaccount1;
      - ConnectionStrings__RedisCache=svc.cache.local:6379
      - RabbitMQ__Host=svc.msgque.local
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - AppUrlRoot=http://127.0.0.1:10000/devstoreaccount1
      - OtlpUrl=http://svc.jaeger.local:4318

  reportingengine:
    container_name: app.reportingengine
    profiles:
      - reporting
      - platform
      - api
      - app
    build:
      context: ./src/SOL.Reporting/SOL.Reporting
      dockerfile: Dockerfile
    hostname: app.reportingengine.local
    ports:
      - 5052:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CustomerDb=Server=svc.sqldb.local;Database=CustomerDb;User Id=sa;Password=P@ssw0rd!;Persist Security Info=False;Encrypt=False

  linesapp:
    container_name: app.lines
    profiles:
      - app    
    build: 
      context: ../LinesApp
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:5051/graphql/
        - VITE_WS_API_URL=ws://localhost:5051/graphql/
        - VITE_REPORT_SERVICE_URL=http://localhost:5052
        - GQL_SCHEMA_PATH=http://host.docker.internal:5051/graphql/
    depends_on:
      - platform
      - reportingengine
    hostname: app.lines.local
    ports:
      - 5050:80

  dataseeder:
    container_name: app.seeder
    profiles:
      - platform
      - seeder
    build:
      context: ./dbo
      dockerfile: Dockerfile
    depends_on:
      - mssqltools

  mssqltools:
    container_name: svc.sqltools
    image: mcr.microsoft.com/mssql-tools
    profiles:
      - platform
      - seeder
    command: /bin/bash -c '/opt/mssql-tools/bin/sqlcmd -S svc.sqldb.local -U sa -P "P@ssw0rd!" -Q "USE master; ALTER DATABASE [CustomerDb] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [CustomerDb];";'
    depends_on:
      - azuresql

  rabbitmq:
    container_name: svc.msgque
    image: masstransit/rabbitmq:3.13.1
    hostname: svc.msgque.local
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 3s

  redis:
    container_name: svc.cache
    image: redis/redis-stack:7.4.0-v0
    hostname: svc.cache.local
    ports:
      - 6379:6379
      - 8001:8001
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 3s

  azuresql:
    container_name: svc.sqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: svc.sqldb.local
    platform: linux/amd64
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd!
      - MSSQL_PID=Developer
#    healthcheck:
#      test: ["CMD", "sqlcmd", "-U", "sa", "-P", "P@ssw0rd!", "-Q", "SELECT 1"]
#      interval: 5s
#      timeout: 10s
#      retries: 5
#      start_period: 3s

  azurestorage:
    container_name: svc.storage
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log'
    hostname: svc.storage.local
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    healthcheck: 
      test: nc 127.0.0.1 10000 -z
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 3s
    volumes:
      - ./azurite:/workspace

  jaeger:
    container_name: svc.jaeger
    image: jaegertracing/jaeger:2.2.0
    hostname: svc.jaeger.local
    ports:
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 5778:5778
      - 9411:9411