name: Database CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  SOLUTION_PATH: Platform/tst/SOL.Service.PatientEncounter.Tests/SalubrityOnline.sln
  SQL_PROJECT_PATH: Platform/dbo/SOL.Database.Tenant/SOL.Database.Tenant.sqlproj
  DOCKERFILE_PATH: Platform/dbo/Dockerfile
  WORKING_DIR: Platform/dbo

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Solution
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          msbuild "${{ github.workspace }}/${{ env.SOLUTION_PATH }}" \
          /p:Configuration=Release \
          /p:TargetFrameworkVersion=v4.7.1"

      - name: Verify DACPAC Output
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          ls -R "${{ github.workspace }}/Platform/dbo/SOL.Database.Tenant/bin/Release/"

      - name: Upload DACPAC Artifact
        uses: actions/upload-artifact@v3
        with:
          name: database-package
          path: ${{ github.workspace }}/Platform/dbo/SOL.Database.Tenant/bin/Release/SOL.Database.Tenant.dacpac

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: database-package
          path: ${{ github.workspace }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Database
        uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.CONNECTION_STRING }}
          path: ${{ github.workspace }}/SOL.Database.Tenant.dacpac
          action: publish
          arguments: '/p:DropObjectsNotInSource=true /p:BlockOnPossibleDataLoss=true'