name: Database CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-db:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Database Project
        run: |
          msbuild Platform/dbo/SOL.Database.Tenant/SOL.Database.Tenant.sqlproj /p:Configuration=Debug /p:TargetFrameworkVersion=v4.7.1
        shell: powershell

      - name: Copy DACPAC to Staging Directory
        run: |
          New-Item -ItemType Directory -Path staging -Force
          Copy-Item -Path Platform/dbo/SOL.Database.Tenant/bin/Debug/*.dacpac -Destination staging
        shell: powershell

      - name: Upload DACPAC Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dropDacpac
          path: staging

  deploy-db:
    runs-on: windows-latest #self-hosted
    needs: build-db
    environment: dbaverificationscript
    steps:
      - name: Download DACPAC Artifact
        uses: actions/download-artifact@v4
        with:
          name: dropDacpac
          path: staging

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Database
        uses: Azure/sql-action@v2.3
        with:
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: 'staging/SOL.Database.Tenant.dacpac'
          action: 'publish'
          arguments: '/p:DropObjectsNotInSource=true /p:BlockOnPossibleDataLoss=true'