name: Platform Service CI/CD

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'  
  PROJECT_PATH: Platform/src/SOL.Gateway/SOL.Gateway.csproj
  DOCKERFILE_PATH: Platform/src/Dockerfile
  BUILD_OUTPUT_PATH: Platform/src/SOL.Gateway/publish
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_NAME: platform-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.BUILD_OUTPUT_PATH }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: platform-service-artifact
          path: ${{ env.BUILD_OUTPUT_PATH }}

  docker-build-and-push:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 🔍 Check & Install Docker (if missing)
        run: |
          if (!(Get-Command docker -ErrorAction SilentlyContinue)) {
            Write-Host "❌ Docker is not installed. Installing Docker..."
            Invoke-WebRequest -Uri "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe" -OutFile "$env:TEMP\DockerInstaller.exe"
            Start-Process -FilePath "$env:TEMP\DockerInstaller.exe" -ArgumentList "install", "--quiet", "--norestart" -Wait
            Write-Host "✅ Docker installation completed!"
          } else {
            Write-Host "✅ Docker is already installed!"
          }
        shell: pwsh

      - name: 🚀 Start Docker Service (Windows only)
        if: runner.os == 'Windows'
        run: |
          Write-Host "Checking if Docker service is running..."
          $service = Get-Service docker -ErrorAction SilentlyContinue
          if ($service -and $service.Status -ne 'Running') {
            Write-Host "🚀 Starting Docker..."
            Start-Service docker
            Start-Sleep -s 10  # Wait for Docker to start
          } else {
            Write-Host "✅ Docker is already running!"

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ env.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -f ${{ env.DOCKERFILE_PATH }} ${{ env.PLATFORM_PROJECT_PATH }}
          docker tag ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Image to ACR
        run: |
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
